# Generated by Django 2.0.6 on 2019-06-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
